spring.datasource.url=jdbc:postgresql://localhost:5432/bakery
spring.datasource.username=bakery
spring.datasource.password=bakery
spring.sql.init.platform=postgresql
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=false
