#Vaadin Copilot Integration Runtime Properties
#Fri Sep 04 12:44:58 EEST 2026
endpoint=http\://127.0.0.1\:60670/vaadin/copilot-b0587f3c-a5e4-45bd-be42-187d584d4e03
supportedActions=write,writeBase64,delete,undo,redo,refresh,showInIde,getModulePaths,compileFiles,restartApplication,getVaadinRoutes,getVaadinVersion,getVaadinComponents,getVaadinEntities,getVaadinSecurity,reloadMavenModule,heartbeat
ide=eclipse
version=1.0.0
